services:
  - type: web
    name: html-to-pdf-service
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    disk:
      name: pdf-service-disk
      mountPath: /tmp
      sizeGB: 1
